version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "10086:10086"
#    volumes:
#      - ./backend:/app
#    environment:
#      - DEV_DATABASE_URL=postgresql://username:password@host:port/database
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d

networks:
  default:
    driver: bridge
